spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/shopping_test?serverTimezone=GMT
    username: root
    password: 123456
  application:
    name: product-service
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        cluster-name: HZ
logging:
  level:
    web: debug
    com.wujie: debug


pagehelper:
  reasonable: true
mapper:
  identity: MYSQL

server:
  port: 8100
  servlet:
    context-path: /
