#spring:
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/shopping_test?serverTimezone=GMT
#    username: root
#    password: 123456
#  application:
#    name: cart-service

#  cloud:
#    nacos:
#      server-addr: localhost:8848
#    loadbalancer:
#      nacos:
#        enabled: true
#logging:
#  level:
#    com.wujie: debug


pagehelper:
  reasonable: true
mapper:
  identity: MYSQL

server:
  port: 9090
  servlet:
    context-path: /
feign:
  okhttp:
    enabled: true

